/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta1

import (
	"k8s.io/apimachinery/pkg/conversion"
	"k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1"
)

// Convert_v1beta1_FlunderSpec_To_v1alpha1_FlunderSpec is an autogenerated conversion function.
func Convert_v1beta1_FlunderSpec_To_v1alpha1_FlunderSpec(in *FlunderSpec, out *v1alpha1.FlunderSpec, s conversion.Scope) error {
	switch in.ReferenceType {
	case FlunderReferenceType:
		t := v1alpha1.FlunderReferenceType
		out.ReferenceType = &t
		out.Reference = in.FlunderReference
	case FischerReferenceType:
		t := v1alpha1.FischerReferenceType
		out.ReferenceType = &t
		out.Reference = in.FischerReference
	}
	return nil
}

// Convert_v1alpha1_FlunderSpec_To_v1beta1_FlunderSpec is an autogenerated conversion function.
func Convert_v1alpha1_FlunderSpec_To_v1beta1_FlunderSpec(in *v1alpha1.FlunderSpec, out *FlunderSpec, s conversion.Scope) error {
	if in.ReferenceType != nil {
		// assume that ReferenceType is defaulted
		switch *in.ReferenceType {
		case v1alpha1.FlunderReferenceType:
			out.ReferenceType = FlunderReferenceType
			out.FlunderReference = in.Reference
		case v1alpha1.FischerReferenceType:
			out.ReferenceType = FischerReferenceType
			out.FischerReference = in.Reference
		}
	}
	return nil
}
