// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1alpha1 "k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Flunder)(nil), (*v1alpha1.Flunder)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Flunder_To_v1alpha1_Flunder(a.(*Flunder), b.(*v1alpha1.Flunder), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Flunder)(nil), (*Flunder)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Flunder_To_v1beta1_Flunder(a.(*v1alpha1.Flunder), b.(*Flunder), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FlunderList)(nil), (*v1alpha1.FlunderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FlunderList_To_v1alpha1_FlunderList(a.(*FlunderList), b.(*v1alpha1.FlunderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.FlunderList)(nil), (*FlunderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FlunderList_To_v1beta1_FlunderList(a.(*v1alpha1.FlunderList), b.(*FlunderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FlunderSpec)(nil), (*v1alpha1.FlunderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FlunderSpec_To_v1alpha1_FlunderSpec(a.(*FlunderSpec), b.(*v1alpha1.FlunderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.FlunderSpec)(nil), (*FlunderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FlunderSpec_To_v1beta1_FlunderSpec(a.(*v1alpha1.FlunderSpec), b.(*FlunderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FlunderStatus)(nil), (*v1alpha1.FlunderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FlunderStatus_To_v1alpha1_FlunderStatus(a.(*FlunderStatus), b.(*v1alpha1.FlunderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.FlunderStatus)(nil), (*FlunderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FlunderStatus_To_v1beta1_FlunderStatus(a.(*v1alpha1.FlunderStatus), b.(*FlunderStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Flunder_To_v1alpha1_Flunder(in *Flunder, out *v1alpha1.Flunder, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_FlunderSpec_To_v1alpha1_FlunderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_FlunderStatus_To_v1alpha1_FlunderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Flunder_To_v1alpha1_Flunder is an autogenerated conversion function.
func Convert_v1beta1_Flunder_To_v1alpha1_Flunder(in *Flunder, out *v1alpha1.Flunder, s conversion.Scope) error {
	return autoConvert_v1beta1_Flunder_To_v1alpha1_Flunder(in, out, s)
}

func autoConvert_v1alpha1_Flunder_To_v1beta1_Flunder(in *v1alpha1.Flunder, out *Flunder, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_FlunderSpec_To_v1beta1_FlunderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_FlunderStatus_To_v1beta1_FlunderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Flunder_To_v1beta1_Flunder is an autogenerated conversion function.
func Convert_v1alpha1_Flunder_To_v1beta1_Flunder(in *v1alpha1.Flunder, out *Flunder, s conversion.Scope) error {
	return autoConvert_v1alpha1_Flunder_To_v1beta1_Flunder(in, out, s)
}

func autoConvert_v1beta1_FlunderList_To_v1alpha1_FlunderList(in *FlunderList, out *v1alpha1.FlunderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha1.Flunder, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Flunder_To_v1alpha1_Flunder(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_FlunderList_To_v1alpha1_FlunderList is an autogenerated conversion function.
func Convert_v1beta1_FlunderList_To_v1alpha1_FlunderList(in *FlunderList, out *v1alpha1.FlunderList, s conversion.Scope) error {
	return autoConvert_v1beta1_FlunderList_To_v1alpha1_FlunderList(in, out, s)
}

func autoConvert_v1alpha1_FlunderList_To_v1beta1_FlunderList(in *v1alpha1.FlunderList, out *FlunderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Flunder, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Flunder_To_v1beta1_Flunder(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_FlunderList_To_v1beta1_FlunderList is an autogenerated conversion function.
func Convert_v1alpha1_FlunderList_To_v1beta1_FlunderList(in *v1alpha1.FlunderList, out *FlunderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_FlunderList_To_v1beta1_FlunderList(in, out, s)
}

func autoConvert_v1beta1_FlunderSpec_To_v1alpha1_FlunderSpec(in *FlunderSpec, out *v1alpha1.FlunderSpec, s conversion.Scope) error {
	// WARNING: in.FlunderReference requires manual conversion: does not exist in peer-type
	// WARNING: in.FischerReference requires manual conversion: does not exist in peer-type
	// WARNING: in.ReferenceType requires manual conversion: inconvertible types (k8s.io/sample-apiserver/pkg/apis/wardle/v1beta1.ReferenceType vs *k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1.ReferenceType)
	return nil
}

func autoConvert_v1alpha1_FlunderSpec_To_v1beta1_FlunderSpec(in *v1alpha1.FlunderSpec, out *FlunderSpec, s conversion.Scope) error {
	// WARNING: in.Reference requires manual conversion: does not exist in peer-type
	// WARNING: in.ReferenceType requires manual conversion: inconvertible types (*k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1.ReferenceType vs k8s.io/sample-apiserver/pkg/apis/wardle/v1beta1.ReferenceType)
	return nil
}

func autoConvert_v1beta1_FlunderStatus_To_v1alpha1_FlunderStatus(in *FlunderStatus, out *v1alpha1.FlunderStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_FlunderStatus_To_v1alpha1_FlunderStatus is an autogenerated conversion function.
func Convert_v1beta1_FlunderStatus_To_v1alpha1_FlunderStatus(in *FlunderStatus, out *v1alpha1.FlunderStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_FlunderStatus_To_v1alpha1_FlunderStatus(in, out, s)
}

func autoConvert_v1alpha1_FlunderStatus_To_v1beta1_FlunderStatus(in *v1alpha1.FlunderStatus, out *FlunderStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_FlunderStatus_To_v1beta1_FlunderStatus is an autogenerated conversion function.
func Convert_v1alpha1_FlunderStatus_To_v1beta1_FlunderStatus(in *v1alpha1.FlunderStatus, out *FlunderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_FlunderStatus_To_v1beta1_FlunderStatus(in, out, s)
}
